spring:
    application:
        name: onlineOrderingSystemFromAutoPartsSuppliers
    datasource:
        url: jdbc:postgresql://localhost:5432/onlineOrderingSystemFromAutoPartsSuppliers
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    liquibase:
        change-log: classpath:/db.changelog/changelog-master.xml



